[project]
name = "gemmapreduce"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
  "jupyter>=1.1.1",
  "numpy>=2.2.6",
  "torch>=2.7.0",
]
